### PR TITLE
issues 46

### PR DESCRIPTION
**Pull request by Der-Orden**
"ephemeral" was missing in (EC)DHE long description

### CODE REVIEW

**Comment by rugk** [comment]
Fixes https://github.com/sibiantony/ssleuth/issues/46

**Comment by rugk** [comment]
FYI if you [add text](https://help.github.com/articles/closing-issues-via-commit-messages/) like "fixes #46" in the description or title of this Pull Request here, the issue will be automatically closed when this Pull Request is merged.

**Comment by rugk** [comment]
Anyone wanting to merge this?

**Comment by sibiantony** [comment]
@rugk I wanted to re-design the panel before merging this. At the moment, if we merge the above, it will just result in a bloated-looking panel. Or else, we need something like tooltips to display as you suggested in the ticket.
Things had been keeping me busy, so please be patient.

**Comment by sibiantony** [comment]
I have merged the PR,  and not happy with the length the above text brings in to the current panel.
So I will work on making this into a tooltip or so. 
Meanwhile, much of this delay was due to e10s support (and is finally here for SSleuth)! I hope to work on new features now that it is over. The e10s version should be out as soon as review is completed at addons.mozilla.org

**Pull request merged**
