### PR TITLE
Translated missing strings to German

### PR DESCRIPTION
**Pull request by jeifour**
I made an effort to translate the newly exposed string into German. I will ask some friends for proof-reading in the next weeks and contribute any corrections. Some things that are still only in English:

* Explanations like "Reportedly weak."
* Names of the standard cipher suite lists ("RC4 suites" etc.)
* The right-click menu of the notifier
* In the options the link leading to [the wiki page about cipher suite lists](https://github.com/sibiantony/ssleuth/wiki/Cipher-suites-enabling-and-disabling)

And some stuff showed up in English during my testing which I thought I had translated:
* Connection status (Secure, Insecure) still showed up in English
* In the options the buttons for "default", "enable" and "disable"

### CODE REVIEW

**Comment by Der-Orden** [comment]
Quick look says: looks good.

**Comment by sibiantony** [comment]
Awesome. Thanks @jeifour ! And thanks @Der-Orden for the review.

* Explanation notes under cipher suites : I've added new strings to the properties file.
* Names of the lists - This one is actually a preferences entry. Can be edited by the user if need be, and wasn't meant for localization. 
* Right-click menu : I was originally planning to remove the right-click menu by bringing all those options to the panel. The menu is also not that obvious as per feedback by other users. Any ways, I've added the menu strings, should work with translations.
* Link to project wiki - Added new string..
* Connection status text - fixed.
* 'default', 'enable' and 'disable' - Added new strings. 

In addition, there is also a description text in `install.rdf`. I've created a new entry for de-DE.

**Comment by jeifour** [comment]
The right-click menu is indeed not very obvious. I'm using SSleuth for quite some time now on all my machines and only discovered it when translating these strings yesterday. (It is introduced in ssleuth.pref.ciphersuites.desc1) I personally think it isn't really needed, so if nobody else cares about it, I would also favor removing it.

**Comment by sibiantony** [comment]
Yes, I agree. I have to move the other options ('Reset All', 'Custom list' etc.) as buttons in the cipher suites tab. Should be straightforward to do, but was of least priority. Anyways, I'll remove it in a future release. And if you're translating, translate the menu strings too, I can re-use them in buttons later.

**Pull request merged**
